server:
  port: 8082
spring:
  application:
    name: hm-api-service
  cloud:
    nacos:
      server-addr: ${hm.nacos.server-addr}
  profiles:
    active: dev
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
    # 可以确保不同的服务输出的日志的名字不一样，这也是为什么我们需要qpplication.name的原因
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
feign:
  okhttp:
    enabled: true # 开启OkHttp作为Feign的客户端